-- Creación de tablas base requeridas por el modelo si no existen
CREATE TABLE IF NOT EXISTS hotwheels (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Nombre" text NOT NULL,
    "Modelo" text NOT NULL,
    "PrecioBase" numeric NOT NULL,
    "Rareza" text NOT NULL
);

CREATE TABLE IF NOT EXISTS proyecciones (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CurrentValue" numeric NOT NULL,
    "Year1" numeric NOT NULL,
    "Year5" numeric NOT NULL,
    "Year10" numeric NOT NULL,
    "Year20" numeric NOT NULL,
    "HotwheelId" integer NOT NULL UNIQUE,
    CONSTRAINT "FK_proyecciones_hotwheels_HotwheelId" FOREIGN KEY ("HotwheelId") REFERENCES hotwheels ("Id") ON DELETE CASCADE
);

-- Limpieza preventiva para evitar datos duplicados si el script se corre múltiples veces
TRUNCATE TABLE proyecciones, hotwheels RESTART IDENTITY CASCADE;

-- Inserción de catálogo maestro semilla
INSERT INTO hotwheels ("Nombre", "Modelo", "PrecioBase", "Rareza")
VALUES 
    ('Lamborghini Miura S (Chase)', '1971', 500.00, 'RLC'),
    ('Tesla Cybertruck', '2023', 80.00, 'Mainline'),
    ('Custom ''69 Chevy', '2021', 150.00, 'STH');
