CREATE TABLE IF NOT EXISTS categories (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Nombre" text NOT NULL,
    "Descripcion" text NOT NULL
);

CREATE TABLE IF NOT EXISTS hotwheels (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Nombre" text NOT NULL,
    "Modelo" text NOT NULL,
    "PrecioBase" numeric NOT NULL,
    "Rareza" text NOT NULL,
    "CategoryId" integer NOT NULL,
    CONSTRAINT "FK_hotwheels_categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES categories ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS proyecciones (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CurrentValue" numeric NOT NULL,
    "Year1" numeric NOT NULL,
    "Year5" numeric NOT NULL,
    "Year10" numeric NOT NULL,
    "Year20" numeric NOT NULL,
    "HotwheelId" integer NOT NULL UNIQUE,
    CONSTRAINT "FK_proyecciones_hotwheels_HotwheelId" FOREIGN KEY ("HotwheelId") REFERENCES hotwheels ("Id") ON DELETE CASCADE
);

TRUNCATE TABLE proyecciones, hotwheels, categories RESTART IDENTITY CASCADE;

INSERT INTO categories ("Nombre", "Descripcion")
VALUES 
    ('Línea Básica', 'Modelos de producción masiva y venta regular.'),
    ('Ediciones Especiales de Colección', 'Modelos limitados, exclusivos o de membresías.');

INSERT INTO hotwheels ("Nombre", "Modelo", "PrecioBase", "Rareza", "CategoryId")
VALUES 
    ('Lamborghini Miura S (Chase)', '1971', 500.00, 'RLC', 2),
    ('Tesla Cybertruck', '2023', 80.00, 'Mainline', 1),
    ('Custom ''69 Chevy', '2021', 150.00, 'STH', 2);
