-- Limpieza total del esquema en orden jerárquico de dependencias
DROP TABLE IF EXISTS proyecciones CASCADE;
DROP TABLE IF EXISTS hotwheels CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS factores_externos CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;

-- Tabla de gestión de acceso y roles del sistema
CREATE TABLE usuarios (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Nombre" text NOT NULL,
    "Email" text NOT NULL UNIQUE,
    "Password" text NOT NULL,
    "Rol" text NOT NULL CHECK ("Rol" IN ('Administrador', 'Coleccionista'))
);

-- Tabla de clasificación taxonómica del catálogo
CREATE TABLE categories (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Nombre" text NOT NULL,
    "Descripcion" text NOT NULL
);

-- Tabla principal del inventario de vehículos coleccionables
CREATE TABLE hotwheels (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Nombre" text NOT NULL,
    "Modelo" text NOT NULL,
    "PrecioBase" numeric NOT NULL,
    "Rareza" text NOT NULL,
    "CategoryId" integer NOT NULL,
    CONSTRAINT "FK_hotwheels_categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES categories ("Id") ON DELETE CASCADE
);

-- Tabla de almacenamiento de proyecciones financieras calculadas
CREATE TABLE proyecciones (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CurrentValue" numeric NOT NULL,
    "Year1" numeric NOT NULL,
    "Year5" numeric NOT NULL,
    "Year10" numeric NOT NULL,
    "Year20" numeric NOT NULL,
    "HotwheelId" integer NOT NULL UNIQUE,
    CONSTRAINT "FK_proyecciones_hotwheels_HotwheelId" FOREIGN KEY ("HotwheelId") REFERENCES hotwheels ("Id") ON DELETE CASCADE
);

-- Tabla de variables macroeconómicas que alimentan el motor MSVP
CREATE TABLE factores_externos (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "NombreFactor" varchar(200) NOT NULL,
    "ImpactoPorcentaje" numeric NOT NULL
);

-- Semilla de usuarios del sistema
INSERT INTO usuarios ("Nombre", "Email", "Password", "Rol") VALUES
('Admin General', 'admin@hotwheels.com', 'Admin123', 'Administrador'),
('Josué Collector', 'collector@hotwheels.com', 'Collector123', 'Coleccionista');

-- Semilla de categorías de clasificación
INSERT INTO categories ("Nombre", "Descripcion") VALUES
('Línea Básica', 'Modelos de producción masiva y venta regular.'),
('Ediciones Especiales de Colección', 'Modelos limitados, exclusivos o de membresías.'),
('Cultura Pop y Películas', 'Vehículos icónicos de películas, series y videojuegos.');

-- Semilla de factores externos macroeconómicos
INSERT INTO factores_externos ("NombreFactor", "ImpactoPorcentaje") VALUES
('Efecto Película Mattel', 0.12),
('Aniversario de la Serie', 0.08),
('Inflación del Mercado Coleccionista', 0.05),
('Demanda en Subastas Internacionales', 0.10);

-- Semilla del catálogo maestro de vehículos
INSERT INTO hotwheels ("Nombre", "Modelo", "PrecioBase", "Rareza", "CategoryId") VALUES
('Lamborghini Miura S (Chase)', '1971', 500.00, 'RLC', 2),
('Tesla Cybertruck', '2023', 80.00, 'Mainline', 1),
('Custom ''69 Chevy', '2021', 150.00, 'STH', 2),
('Nissan Skyline GT-R R34', '1999', 250.00, 'STH', 2),
('Batmobile (The Dark Knight)', 'Tumbler', 15.00, 'Mainline', 3),
('DeLorean Time Machine', '1981', 25.00, 'Mainline', 3),
('Datsun Bluebird 510 Wagon', '1971', 300.00, 'RLC', 2),
('Porsche 911 GT3 RS', '2016', 50.00, 'Mainline', 1),
('Volkswagen Drag Bus', '1996', 400.00, 'RLC', 2);
